account/urls.py
from django.urls import path
from . import views

app_name = 'account'


urlpatterns = [
    path("",views.AdminPanelView.as_view(),name="admin_panel"),
    path("notifications/",views.NotificationsView.as_view(),name="notifications"),
]

core/urls.py
# from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# import doctors


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("account.urls")),
    path("doctor/",include("doctors.urls")),
    path("patient/",include("patients.urls")),
    path("disease/",include("disease.urls")),
    path("todo/",include("todo.urls"))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

disease/urls.py
from django.urls import path
from . import views

app_name = "disease"

urlpatterns = [
    path("panel/<str:id>",views.OperationPanelView.as_view(),name = "panel"),
    path("list/",views.OperationListView.as_view(),name = "list"),
    path("create_operation/",views.OperationCreateView.as_view(),name = "create"),
    path("active-deactivate-opration/<str:id>",views.ActivateDeactivateOperation.as_view(),name = "activate_deactivate"),
    path("active-operations",views.ActiveOperationsListView.as_view(),name = "active_operations"),
]

doctors/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'doctor'

# path("admin_register/",views.admin_register),
# path("admin_login/",views.admin_login),


urlpatterns = [
    path("admin_permission_waiting/",views.admin_permission_waiting,name = "admin_permission_waiting"),
    path("admin_permission_accepted/",views.admin_permission_accepted,name = "admin_permission_accepted"),
    

    path("panel/<int:id>",views.DoctorPanelView.as_view(),name = "panel"),
    path("list/",views.DoctorListView.as_view(),name = "list"),
    path("edit/<str:id>",views.DoctorEditView.as_view(),name = "edit"),
    path("logs/<str:id>",views.DoctorLogs.as_view(),name = "logs"),
    path("register/",views.DoctorUserRegister.as_view(), name = "register"),
    path("create/",views.DoctorCreateView.as_view(), name = "create"),
    path("login/",views.DoctorLoginView.as_view(), name = "login"),
    path("logout/",views.DoctorLogoutView.as_view(), name = "logout"),
    path("activate-deactivate-doctor/<str:id>", views.ActivateDeactivateDoctorView.as_view(), name="activate_deactivate"),
    
    path("patients/<str:id>",views.PatientsOfDoctorView.as_view(),name="patients"),
    path("operations/<str:id>",views.OperatationsOfDoctorView.as_view(),name="operations"),

    # path("charts/",views.charts),
    # path("forms",views.forms),
    # path("icons",views.icons),
    # path("tables",views.tables),
    path("ui_features",views.ui_features),
    path("ui_features2",views.ui_features2),
    path("ui_features3",views.ui_features3),
]

patients/urls.py
from . import views
from django.urls import path

app_name  = "patient"

urlpatterns = [
    path("create/",views.PatientCreateView.as_view(), name = "create"),
    path("list/",views.PatientListView.as_view() ,name = "list"),
    path("panel/<str:id>",views.PatientPanelView.as_view(), name = "panel"),
    path("edit/<str:id>",views.PatientEditView.as_view(), name = "edit"),
    path("add_status/<str:id>",views.AddPatientStatusView.as_view(),name = "add_status"),
    path("add_ppl_with_patient/<str:id>",views.AddPplWithPatientView.as_view(),name = "add_ppl_with_patient"),
    path("list_ppl_with_patient/<str:id>",views.ListPplWithPatientView.as_view(),name = "list_ppl_with_patient"),
    path("logs/<str:id>",views.PatientLogsView.as_view(),name = "logs"),
    path("activate-deactivate-patient/<str:id>",views.ActivateDeactivatePatientView.as_view(),name = "activate_deactivate"),
]

templates/includes/_footer.html
<footer class="footer">
  <div class="d-sm-flex justify-content-center justify-content-sm-between">
    <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2020</span>
    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap dashboard template</a> from Bootstrapdash.com</span>
  </div>
</footer>

templates/includes/_navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">
<nav class="navbar col-lg-12 col-12 p-lg-0 fixed-top d-flex flex-row">
  <div class="navbar-menu-wrapper d-flex align-items-stretch justify-content-between">
    <a class="navbar-brand brand-logo-mini align-self-center d-lg-none" href="/"><img src="{% static 'images/logo-mini.svg' %} " alt="logo" /></a>
    <button class="navbar-toggler navbar-toggler align-self-center mr-2" type="button" data-toggle="minimize">
      <i class="mdi mdi-menu"></i>
    </button>
    <ul class="navbar-nav">
      {% comment %} <li class="nav-item dropdown">
        <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
          <i class="mdi mdi-bell-outline"></i>
          <span class="count count-varient1">7</span>
        </a>
        <div class="dropdown-menu navbar-dropdown navbar-dropdown-large preview-list" aria-labelledby="notificationDropdown">
          <h6 class="p-3 mb-0 ">Notifications</h6>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <img src="assets/images/faces/face4.jpg" alt="" class="profile-pic">
            </div>
            <div class="preview-item-content">
              <p class="mb-0">Dany Miles <span class="text-small text-muted">commented on your photo</span></p>
            </div>
          </a>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <img src="assets/images/faces/face3.jpg" alt="" class="profile-pic">
            </div>
            <div class="preview-item-content">
              <p class="mb-0">James <span class="text-small text-muted">posted a photo on your wall</span></p>
            </div>
          </a>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <img src="assets/images/faces/face2.jpg" alt="" class="profile-pic">
            </div>
            <div class="preview-item-content">
              <p class="mb-0">Alex <span class="text-small text-muted">just mentioned you in his post</span></p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <p class="p-3 mb-0 ">View all activities</p>
        </div>
      </li> {% endcomment %}
      {% comment %} <a href="/s"> {% endcomment %}
        {% if user.is_staff == True %}
        <li class="nav-item dropdown d-none d-sm-flex">
          <a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="{% url 'account:notifications' %}">
            <i class="mdi mdi-email-outline"></i>
            <span class="count  count-varient2">{{unaccepted_users.count}}</span>
          </a>
          {% comment %} <div class="dropdown-menu navbar-dropdown navbar-dropdown-large preview-list" aria-labelledby="messageDropdown">
            <h6 class="p-3 mb-0 ">Messages</h6>
            <a class="dropdown-item preview-item">
              <div class="preview-item-content flex-grow">
                <span class="badge badge-pill badge-success">Request</span>
                <p class="text-small text-muted ellipsis mb-0"> Suport needed for user123 </p>
              </div>
              <p class="text-small text-muted align-self-start">4:10 PM</p>
            </a>
            <a class="dropdown-item preview-item">
              <div class="preview-item-content flex-grow">
                <span class="badge badge-pill badge-warning">Invoices</span>
                <p class="text-small text-muted ellipsis mb-0"> Invoice for order is mailed </p>
              </div>
              <p class="text-small text-muted align-self-start">4:10 PM</p>
            </a>
            <a class="dropdown-item preview-item">
              <div class="preview-item-content flex-grow">
                <span class="badge badge-pill badge-danger">Projects</span>
                <p class="text-small text-muted ellipsis mb-0"> New project will start tomorrow </p>
              </div>
              <p class="text-small text-muted align-self-start">4:10 PM</p>
            </a>
            <h6 class="p-3 mb-0 ">See all activity</h6>
          </div> {% endcomment %}
        </li> 
        {% else %}
        
        {% endif %}

      {% comment %} </a> {% endcomment %}
      
      <li class="nav-item nav-search border-0 ml-1 ml-md-3 ml-lg-5 d-none d-md-flex">
        <form class="nav-link form-inline mt-2 mt-md-0">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search">
            <div class="input-group-append">
              <span class="input-group-text">
                <i class="mdi mdi-magnify"></i>
              </span>
            </div>
          </div>
        </form>
      </li>
    </ul>
    <ul class="navbar-nav navbar-nav-right ml-lg-auto">
      {% comment %} <li class="nav-item dropdown d-none d-xl-flex border-0">
        <a class="nav-link dropdown-toggle" id="languageDropdown" href="#" data-toggle="dropdown">
          <i class="mdi mdi-earth"></i> English </a>
        <div class="dropdown-menu navbar-dropdown" aria-labelledby="languageDropdown">
          <a class="dropdown-item" href="#"> French </a>
          <a class="dropdown-item" href="#"> Spain </a>
          <a class="dropdown-item" href="#"> Latin </a>
          <a class="dropdown-item" href="#"> Japanese </a>
        </div>
      </li> {% endcomment %}
      <li class="nav-item  nav-profile dropdown border-0">
        <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown">
          <img class="nav-profile-img mr-2" alt="" src="{% static 'images/faces/face1.jpg' %}">
          <span class="profile-name">{{user.email}}</span>
        </a>
        <div class="dropdown-menu navbar-dropdown w-100" aria-labelledby="profileDropdown">
          <a class="dropdown-item" href="#">
            <i class="mdi mdi-logout mr-2 text-primary"></i> Signout </a>
        </div>
      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="mdi mdi-menu"></span>
    </button>
  </div>
</nav>

templates/includes/_settings-panel.html
<div id="theme-settings" class="settings-panel">
  <i class="settings-close mdi mdi-close"></i>
  <p class="settings-heading">SIDEBAR SKINS</p>
  <div class="sidebar-bg-options selected" id="sidebar-default-theme">
    <div class="img-ss rounded-circle bg-light border mr-3"></div> Default
  </div>
  <div class="sidebar-bg-options" id="sidebar-dark-theme">
    <div class="img-ss rounded-circle bg-dark border mr-3"></div> Dark
  </div>
  <p class="settings-heading mt-2">HEADER SKINS</p>
  <div class="color-tiles mx-0 px-4">
    <div class="tiles light"></div>
    <div class="tiles dark"></div>
  </div>
</div>

templates/includes/_sidebar.html
{% load static %}
  <nav class="sidebar sidebar-offcanvas" id="sidebar">
  {% if user.is_anonymous %}
    <div class="text-center sidebar-brand-wrapper d-flex align-items-center">
      Siz Hesab Yaratmali Ve Ya Giris Etmelisiniz
    </div>
  {% else %}
    <div class="text-center sidebar-brand-wrapper d-flex align-items-center">
      {% if user.is_superuser == True %}
        <a class="sidebar-brand brand-logo" href="{% url 'account:admin_panel' %}"><img src="{% static 'images/logo.svg' %} "alt="logo" /></a>
      {% elif user.user_doctors is None %}
        <a class="sidebar-brand brand-logo" href="{% url 'doctor:panel' user.user_doctors.id %}"><img src="{% static 'images/logo.svg' %} "alt="logo" /></a>
      {% endif %}
    </div>
      <ul class="nav">
        <li class="nav-item nav-profile">
          <a href="#" class="nav-link">
            <div class="nav-profile-image">
              <img src="{% static 'images/faces/face1.jpg' %}" alt="profile" />
              <span class="login-status busy"></span>
              <!--change to offline or busy as needed-->
            </div>

            <div class="nav-profile-text d-flex flex-column pr-3">
              {% if user.is_staff == True %}
                <span class="font-weight-medium mb-2">Siz Adminsiniz</span>
                <span class="font-weight-medium mb-2">{{user.email}}</span>
              {% else %}
                <span class="font-weight-medium mb-2">Siz Doctorsunuz</span>
                <span class="font-weight-medium mb-2">{{user.user_doctors}}</span>
              {% endif %}
            </div>
            <span class="badge badge-danger text-white ml-3 rounded">{{unaccepted_users.count}}</span>
          </a>
        </li>
        {% if user.user_doctors %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'doctor:panel' user.user_doctors.id %}">
                <i class="mdi mdi-home menu-icon"></i>
                <span class="menu-title">Dashboard</span>
              </a>
            </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'doctor:patients' user.user_doctors.id %}">
                  <i class="mdi mdi-account-multiple menu-icon"></i>
                  <span class="menu-title">Size Aid Olan Patient'ler</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'doctor:operations' user.user_doctors.id %}">
                  <i class="mdi mdi-briefcase-outline menu-icon"></i>
                  <span class="menu-title">Size Aid Olan Emeliyyatlar</span>
                </a>
              </li>

        {% elif user.is_staff == True %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account:admin_panel' %}">
              <i class="mdi mdi-home menu-icon"></i>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'doctor:list' %}">
              <i class="mdi mdi-contacts menu-icon"></i>
              <span class="menu-title">Hekimler</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'patient:list' %}">
              <i class="mdi mdi-account-multiple menu-icon"></i>
              <span class="menu-title">Patient'ler</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'disease:list' %}">
              <i class="mdi mdi-briefcase-outline menu-icon"></i>
              <span class="menu-title">Emeliyyatlar</span>
            </a>
          </li>


        {% endif %}
        
        {% comment %} <li class="nav-item">
          <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
            <i class="mdi mdi-crosshairs-gps menu-icon"></i>
            <span class="menu-title">Basic UI Elements</span>
            <i class="menu-arrow"></i>
          </a>
          <div class="collapse" id="ui-basic">
            <ul class="nav flex-column sub-menu">
              <li class="nav-item">
                <a class="nav-link" href="pages/ui-features/buttons.html">Buttons</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="pages/ui-features/dropdowns.html">Dropdowns</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="pages/ui-features/typography.html">Typography</a>
              </li>
            </ul>
          </div>
        </li> {% endcomment %}

        {% comment %} <li class="nav-item">
          <a class="nav-link" href="pages/tables/basic-table.html">
            <i class="mdi mdi-table-large menu-icon"></i>
            <span class="menu-title">Tables</span>
          </a>
        </li> {% endcomment %}
        {% comment %} <li class="nav-item">
          <span class="nav-link" href="#">
            <span class="menu-title">Docs</span>
          </span>
        </li> {% endcomment %}
        {% comment %} <li class="nav-item">
          <a class="nav-link" href="https://www.bootstrapdash.com/demo/breeze-free/documentation/documentation.html">
            <i class="mdi mdi-file-document-box menu-icon"></i>
            <span class="menu-title">Documentation</span>
          </a>
        </li> {% endcomment %}
        <li class="nav-item sidebar-actions">
          <div class="nav-link">
            <div class="mt-4">
              {% comment %} <div class="border-none">
                <p class="text-black">Notification</p>
              </div> {% endcomment %}
              {% if user.is_staff == False %}
                <ul class="mt-4 pl-0">
                  <li>
                    <a href="{% url 'doctor:logout' %}">Sign Out</a> 
                  </li>
                </ul>
              {% else %}
                
              {% endif %}

            </div>
          </div>
        </li>
      </ul>
  {% endif %}
</nav>

templates/includes/header_plugins.html
{% load static %}
<link rel="stylesheet"href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/css/intlTelInput.css"/>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/intlTelInput.min.js"></script>

templates/includes/plugins.html
{% load static %}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="{% static 'vendors/chart.js/Chart.min.js' %}"></script>
<script src="{% static 'vendors/flot/jquery.flot.js' %}"></script>
<script src="{% static 'vendors/flot/jquery.flot.resize.js' %}"></script>
<script src="{% static 'vendors/flot/jquery.flot.categories.js' %}"></script>
<script src="{% static 'vendors/flot/jquery.flot.fillbetween.js' %}"></script>
<script src="{% static 'vendors/flot/jquery.flot.stack.js' %}"></script>
<script src="{% static 'vendors/flot/jquery.flot.pie.js' %} "></script>
<script src="{% static 'vendors/js/vendor.bundle.base.js' %} "></script>

<!-- End plugin js for this page -->
<!-- inject:js -->
<script src="{% static 'js/off-canvas.js' %} "></script>
<script src="{% static 'js/hoverable-collapse.js' %}"></script>
<script src="{% static 'js/misc.js' %}"></script>
<!-- endinject -->
<!-- Custom js for this page -->
<script src="{% static 'js/dashboard.js' %}"></script>
<!-- End custom js for this page -->
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>